name: 'Packages Split'

on:
    push:
        # branches:
        #     - master
        tags:
            - '*'
    workflow_dispatch:

env:
    # 1. for Github split
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest
        environment: deployment

        strategy:
            fail-fast: false
            matrix:
                # define package to repository map
                package:
                    -
                        local_path: 'cache'
                        split_repository: 'cache'
                    -
                        local_path: 'framework'
                        split_repository: 'framework'
                    -
                        local_path: 'persistence'
                        split_repository: 'persistence'
                    -
                        local_path: 'metadata'
                        split_repository: 'metadata'
                    -
                        local_path: 'event'
                        split_repository: 'event'
                    -
                        local_path: 'data'
                        split_repository: 'data'
                    -
                        local_path: 'container'
                        split_repository: 'container'
                    -
                        local_path: 'logger'
                        split_repository: 'logger'
                        
        steps:
            - uses: actions/checkout@v2

            -
                if: "startsWith(github.ref, 'refs/tags/')"
                # if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@v2.3.0"
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    # ↓ split "packages/easy-coding-standard" directory
                    package_directory: 'packages/${{ matrix.package.local_path }}'

                    # ↓ into https://github.com/symplify/easy-coding-standard repository
                    repository_organization: 'primavera-php'
                    repository_name: '${{ matrix.package.split_repository }}'

                    # ↓ the user signed under the split commit
                    user_name: "Jhonatan Teixeira"
                    user_email: "jhonatan.teixeira@gmail.com"

                    branch: master
